UPDATE

diff --git a/basher b/basher
--- a/basher
+++ b/basher
@@ -384,20 +384,20 @@ function lookup(){
       clrformat
       elements
       ;;
-    \? )
+    *)
       echo
       echo "Invalid option: ${option}" 1>&2
       echo
       help
       exit 0
       ;;
-    : )
-      echo
-      echo "Invalid option: ${option} requires an argument" 1>&2
-      echo
-      help
-      exit 0
-      ;;
+    # : )
+    #   echo
+    #   echo "Invalid option: ${option} requires an argument" 1>&2
+    #   echo
+    #   help
+    #   exit 0
+    #   ;;
   esac
 }
 
